#4 magic letters moved in constants, created a method filling out the…
AOkhapkina/TicTacToe pull request #16
Opened 2022-02-08 17:41 UTC by AOkhapkina

… matrix (board)

2022-02-08 18:02 UTC, friendlyted commented
Не все вхождения заменила.

2022-02-08 18:08 UTC, friendlyted requested changes

2022-02-08 18:08 UTC, friendlyted commented on src/main/java/MainGame.java
> +            for (int j=0; j<matrix.length;j++)
Тут тебе повезло, что матрица квадратная. 
j<matrix.length - неправильное условие

2022-02-08 19:56 UTC, AOkhapkina commented on src/main/java/MainGame.java
> +            for (int j=0; j<matrix.length;j++)
Я могу здесь закомитить изменение метода заполнения матрицы? Ну и заполнение тоже сюда закомитить?

2022-02-10 08:54 UTC, friendlyted commented on src/main/java/MainGame.java
> +            for (int j=0; j<matrix.length;j++)
Да, в этой задаче давай

2022-02-10 19:44 UTC, alima-t commented on src/main/java/MainGame.java
> +            for (int j=0; j<matrix.length;j++)
Добавила в этой задаче изменение метода

2022-02-19 06:46 UTC, AOkhapkina commented
#4 merged into #18

2022-02-19 06:47 UTC, AOkhapkina commented
#4 merged into #18

2022-02-19 06:47 UTC, closed without merging