#19 A method with a try-catch block added to handle of Exception.
AOkhapkina/TicTacToe pull request #25
Opened 2022-02-12 05:54 UTC by AOkhapkina

#19 A method with a try-catch block added to handle of IndexOutOfBoundsException. Do-while loop added.

2022-02-12 11:35 UTC, friendlyted requested changes

2022-02-12 11:35 UTC, friendlyted commented on src/main/java/MainGame.java
> +            do {
Перевожу на русский, что тут происходит. 
1. Читаем ввод. 
2. Заполняем поле. 
3. Проверяем, заполнено ли поле. 
4. Проверяем, корректным ли был ввод.
5. Если корректный, выход, иначе 1.
Ничего не смущает? :)

2022-02-12 11:35 UTC, friendlyted commented on src/main/java/MainGame.java
> +                if (!checkIfFieldIsFree()) {
Прокомментируй, что делает checkIfFieldIsFree?

2022-02-12 11:35 UTC, friendlyted commented on src/main/java/MainGame.java
> +            do {
Эти два куска кода с do подозрительно похожи

2022-02-12 11:39 UTC, AOkhapkina commented on src/main/java/MainGame.java
> +                if (!checkIfFieldIsFree()) {
Он должен проверять если ячейка с введенными координатами свободна, но я пока писала тест поняла, что в параметрах должна быть доска, наверное, поэтому метод не работает, ему нечего проверять, получается

2022-02-12 11:42 UTC, AOkhapkina commented on src/main/java/MainGame.java
> +            do {
Нужно убрать "!",  он не работал и я пробовала разные варианты, так и осталось в коде.

2022-02-12 11:46 UTC, AOkhapkina commented on src/main/java/MainGame.java
> +            do {
Я пока вот на сегодняшний день не готова это исправить, Федь, я пробовала, не получается, мне кажется что нужно вообще отдельний класс, конструктор для игрока и т.д., переопределять метод под каждого игрока, чтобы изменить сейчас задвоение кода

2022-02-12 11:48 UTC, friendlyted commented on src/main/java/MainGame.java
> +            do {
то есть ничего не смущает, понятно

2022-02-12 11:48 UTC, friendlyted commented on src/main/java/MainGame.java
> +                if (!checkIfFieldIsFree()) {
"ячейка с введенными координатами" - ключевой момент. Проверяй.

2022-02-12 11:49 UTC, friendlyted commented on src/main/java/MainGame.java
> +            do {
Нет, это все иллюзии, не надо пока усложнять ничего без необходимости.

2022-02-12 11:54 UTC, AOkhapkina commented on src/main/java/MainGame.java
> +            do {
Я понимаю, что здесь проблема с методом checkIfFieldIsFree().
Когда я его поправлю будет так: если корректный ввод, то переход хода к другому игроку. 
1 у меня не выходило.

2022-02-12 11:55 UTC, AOkhapkina commented on src/main/java/MainGame.java
> +            do {
если некорретный, то возвращается на начало кода и снова запрашивает ввести координаты у того же игрока

2022-02-12 11:56 UTC, friendlyted commented on src/main/java/MainGame.java
> +                if (!checkIfFieldIsFree()) {
> Он должен проверять если ячейка с введенными координатами свободна
Вот этого он с высокой вероятностью не делает как раз.

2022-02-14 15:02 UTC, friendlyted commented on src/main/java/MainGame.java
> +    static boolean checkIfInputIsCorrect (int v, int h) {
Ты одни и те же проверки делаешь два раза, один раз для вывода сообщений, второй - для true/false. Это не очень.

2022-02-14 15:06 UTC, friendlyted requested changes

2022-02-14 15:06 UTC, friendlyted commented on src/main/java/MainGame.java
> +            if (!(v >= 0 & v <= 2) || !(h >= 0 & h <= 2)) {
Я тут с самого начала гадаю, зачем побитовые операторы?

2022-02-14 15:06 UTC, friendlyted commented on src/main/java/MainGame.java
> +        }catch (Exception ex) {
Когда exception срабатывает?

2022-02-14 15:06 UTC, friendlyted commented on src/main/java/MainGame.java
> +        }catch (Exception ex){
Не должно случиться исключения

2022-02-14 15:08 UTC, friendlyted commented on src/main/java/MainGame.java
> +            if (board[v][h] != " _ ") {
Я ужа писал про сравнения строк?

2022-02-27 16:42 UTC, closed without merging

2022-02-27 16:44 UTC, AOkhapkina commented
merged in issues/25