#24 junit dependencies added to pom.xml
AOkhapkina/TicTacToe pull request #27
Opened 2022-02-16 20:52 UTC by AOkhapkina

2022-02-17 08:57 UTC, friendlyted requested changes

2022-02-17 08:57 UTC, friendlyted commented on pom.xml
> +        <dependency>
Надо определиться с версией и вбрать что-то одно все-таки. И писать в версии RELEASE не надо, лучше писать конкретную версию.

2022-02-17 14:56 UTC, AOkhapkina commented on pom.xml
> +        <dependency>
Я исправила, но почему RELEASE не стоит писать?

2022-02-18 06:20 UTC, friendlyted commented on pom.xml
> +        <dependency>
Потому что это не точная версия, а плавающая, выйдет обновление, и проект **внезапно** перестанет собираться. Такие сюрпризы ни к чему.

2022-03-05 04:35 UTC, merged