#18 magic twos removed from checkInputNums, method edited
AOkhapkina/TicTacToe pull request #28
Opened 2022-02-17 11:22 UTC by AOkhapkina

2022-02-18 06:18 UTC, friendlyted requested changes

2022-02-18 06:18 UTC, friendlyted commented on src/main/java/MainGame.java
>      static boolean checkInputNums (int v, int h) {
а чем занимается этот метод?

2022-02-18 06:28 UTC, AOkhapkina commented on src/main/java/MainGame.java
>      static boolean checkInputNums (int v, int h) {
Проверяет чтобы цифры были в пределах доски.

2022-02-19 07:38 UTC, AOkhapkina commented
#18 merged into issues/19

2022-02-19 07:38 UTC, closed without merging